theme: jekyll-theme-minimal
title: Projects & Portfolio
description: Tom Wolfe, an innovative journalist and novelist whose technicolor, wildly punctuated prose brought to life the worlds of California surfers, car customizers, astronauts and Manhattan’s moneyed status-seekers in works like “The Kandy-Kolored Tangerine-Flake Streamline Baby,” “The Right Stuff” and “Bonfire of the Vanities,” died on Monday in a Manhattan hospital. He was 88.
logo: aliazad.jpg
show_downloads: false
google_analytics:   #[Your Google Analytics tracking ID]
