theme: jekyll-theme-minimal
logo :  /imgs/aliazad.jpg
title: myHUB
description: Ali Azad <br> Data Scientist <br> ali.azad -at- gatech.edu
show_downloads: false
google_analytics:   #[Your Google Analytics tracking ID]
