theme: jekyll-theme-minimal
title: Projects & Portfolio
description: Ali Azad | Data Enthusiast <br> ali.azad -at- gatech.edu
show_downloads: false
google_analytics:   #[Your Google Analytics tracking ID]
