theme: jekyll-theme-minimal
logo :  /_img/aliazad.jpg
title: PORTFOLIO
description: Ali Azad <br> Data Enthusiast <br> ali.azad -at- gatech.edu
show_downloads: false
google_analytics:   #[Your Google Analytics tracking ID]
