theme: jekyll-theme-minimal
logo :  /imgs/aliazad.jpg
title: myHUB
description: Ali Azad <br> Data Scientist <br> delgraph -at- gmail.com
show_downloads: false
google_analytics:   #[Your Google Analytics tracking ID]
