publishDir = "./../"
name = "pulp"
license = "MIT"
description = "Theme description"
homepage = "Website of your theme"
tags = ["blog", "company"]
features = ["some", "awesome", "features"]

[author]
  name = "Ali Azad"
  homepage = "https://a-azad.github.io"